### ISSUE TITLE
Don't stick to Relay

### ISSUE THREAD

**Issue by gyzerok** [fenos/graphql-thinky#1]
Hi @fenos, great work!

My suggestion to the library would be not stick to Relay-GraphQL spec. While Relay is awesome there are a lot of people who use GraphQL without Relay. One thing that is bad in the majority of similar libraries is they use extended GraphQL specification, so people who don't want or unable to use it can't use library at all.

Relay is one way to deal with GraphQL on the client side, not all of them.

**Comment by fenos** [comment]
@gyzerok Thank you very much for your feedback 👍 
The package doesn't force you to use the relay specification, it has built in helpers if needed. 
I may understand that people wouldn't like to pull it if they don't needed, but of course **graphql-thinky** try to follow at least one well maintained specification. As a developer you choose if use it or not :)

Would this be fine for you?

**Comment by gyzerok** [comment]
Yeah, have an ability to decide would be perfect!
