### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ARMGAMES** [fenos/graphql-thinky#11]
Hey, i definetly do something wrong

I attemp to do query at graphiql
```
{
  users{
    name
  }
}
```
and i am getting such error
```
{
  "data": {
    "users": null
  },
  "errors": [
    {
      "message": "Cannot read property '0' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ]
    }
  ]
}
```
**User Model**
```
import thinky from '../thinky';

const { type, r} = thinky;

const User = thinky.createModel("user", {
    id: type.string(),
    name: type.string(),
    age: type.number(),
    sex: type.string(),
    email: type.string(),
    password_digest: type.string(),
    social: type.string(),
    createdAt: type.date().default(r.now())
});

export default User;
```

**UserQuery.js**
```
import { GraphQLList, GraphQLString } from 'graphql';

import UserType from './UserType';
import GraphQLThinky from '../graphql-thinky';

const { resolve } = GraphQLThinky;

export default {
    users : {
        args: {
            name: {
                type: GraphQLString
            }
        },
        type: new GraphQLList( UserType ),
        resolve: resolve( 'user' )
    },
    user : {
        type: UserType,
        args: {
            id: {
                type: GraphQLString
            }
        },
        resolve: resolve( 'user' )
    }
}
```
**UserType.js**
```
import GraphQLThinky from '../graphql-thinky';
export default GraphQLThinky.createModelType('user');
```
**graphql-thinky.js**
```
import GraphQLThinky from 'graphql-thinky';
import models from '../models';
import thinky from '../thinky';

export default new GraphQLThinky(thinky);
```
**Query.js**
```
import UserQuery from './graphql/user/UserQuery';
import GraphqlThinky from './graphql/graphql-thinky';

const Query = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    ...UserQuery,
    node: GraphqlThinky.nodeField
  })
});

export default Query;
```
**Schema.js**
```
import { GraphQLSchema } from 'graphql';
import Query from './query';

const Schema = new GraphQLSchema({
  query: Query,
});

export default Schema;
```
What i do wrong? Thank you for any reply.

P.S.
I have a question about models import at my graphql-thinky file. Why i need to do this before import thinky? And how magicly they attached to thinky. I get this from example.

**Comment by fenos** [comment]
Hi @ARMGAMES The error message doesn't help much, and the implementation of GraphQL schema look good too.

If you are running a `v0.4-*` make sure you check back the documentation and do 1 more step to get running. [#7 reference](https://github.com/fenos/graphql-thinky/issues/7#issuecomment-258410517) 

Then retry on graphiql

**Comment by fenos** [comment]
> I have a question about models import at my graphql-thinky file. Why i need to do this before import thinky? And how magicly they attached to thinky. I get this from example.

When you implement your models you use a single local `thinky` instance, importing it around to create models. Thinky create the model and register it into a property.

We import the models first so that we will `register` them into thinky and `graphql-thinky` can internally make decisions to optimize your queries

**Comment by ARMGAMES** [comment]
Hey @fenos already tryed to add #7, but it changes nothing. Still same error.
I am using v0.4.0-rc-2. Any idea how i can help you to find a problem?

P.S.
The error happens at resolver method, but it happens only when i make a request from graphiql
graphql-thinky\lib\resolver.js:126:68

**Comment by fenos** [comment]
@ARMGAMES thanks for reporting this, I figure out that is a problem with the new graphql `v0.8` there should be a breaking change. I will send a fix today. If you want to start with the library downgrade to graphql `0.7` for the time being.

**Comment by ARMGAMES** [comment]
@fenos Can confirm that all works fine with graphql 0.7

**Comment by fenos** [comment]
Yes all the tests pass and works on the `0.7` I have almost finished the fix for v0.8, there was a renaming field breaking change, from `info.fieldsAST` to `info.fieldNodes` my bad I haven't check it with `0.8`

**Comment by fenos** [comment]
[PR Reference](https://github.com/fenos/graphql-thinky/pull/14) for supporting `Graphql 0.8`
If the CI pass I'll merge and publish `0.4.0-rc-3`

**Comment by fenos** [comment]
Pr Merged, problem fixed
