### ISSUE TITLE
Does not support `[User]!` type

### ISSUE THREAD

**Issue by gutenye** [fenos/graphql-thinky#6]
Given

``` js
var schema = new GraphQLSchema({
   query: new GraphQLObjectType({
    name: "Query",
    fields: {
      users: {
        type: new GraphQLNonNull(GraphQLList(userType))
      }
    }
  }) 
})
```

Got an error.

For it's type is `GraphQLNonNull`,  while the code only check `type instanceof GraphQLList` in https://github.com/fenos/graphql-thinky/blob/master/src/resolver.js#L74

**Comment by fenos** [comment]
Thanks to point out this. I'll work on a fix. 
If u have any other issues please feel free to open as many issues as u like. That help me to improve the library as much as possible.
